---

AWSTemplateFormatVersion: "2010-09-09"

Description: "A custom resource for CloudFormation that enhances integration with Systems Manager Parameter Store"

Resources:

  # IAM role for the Lambda function
  IamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "lambda.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
        - PolicyName: "get-parameters"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "ssm:GetParameters"
                  - "ssm:GetParametersByPath"
                Resource: "*"

  # Lambda function to back the custom resource
  # The code for this function must be managed out of band
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
            raise NotImplementedError('
              Please update this function with the code from index.py
            ')
      Description: "A custom resource for CloudFormation that enhances integration with Systems Manager Parameter Store"
      Handler: "index.lambda_handler"
      MemorySize: 128
      Role: !GetAtt ["IamRole", "Arn"]
      Runtime: "python3.6"
      Timeout: 30
      Environment:
        Variables:
          LOGLEVEL: "info"

  # Systems Manager Parameter Store for the service token
  ServiceTokenParam:
    Type: "AWS::SSM::Parameter"
    Properties:
      Name: "/cloud-formation/service-tokens/cloud-storemation"
      Type: "String"
      Value: !GetAtt ["LambdaFunction", "Arn"]

Outputs:

  ServiceTokenParamKey:
    Description: "The Systems Manager Parameter Store key where the service token is published"
    Value: !Ref "ServiceTokenParam"
